default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary: &primary_development
    <<: *default
    gssencmode: "disable"
    database: homelight_product_development
    username: <%= ENV.fetch('DATABASE_USERNAME', 'postgres') %>
    password: <%= ENV.fetch('DATABASE_PASSWORD', 'postgres') %>
    host: <%= ENV.fetch('DATABASE_HOST', '127.0.0.1') %>
  queue:
    <<: *primary_development
    database: homelight_product_development_queue
    migrations_paths: db/queue_migrate

test:
  primary: &primary_test
    <<: *default
    database: homelight_product_test
    url: <%= ENV["DATABASE_URL"] %>
  queue:
    <<: *primary_test
    database: homelight_product_test_queue
    migrations_paths: db/queue_migrate

staging:
  primary: &primary_staging
    <<: *default
    database: homelight_product_staging
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *primary_staging
    database: homelight_product_staging_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_staging
    database: homelight_product_staging_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_staging
    database: homelight_product_staging_cable
    migrations_paths: db/cable_migrate

production:
  primary: &primary_production
    <<: *default
    database: homelight_product_production
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *primary_production
    database: homelight_product_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: homelight_product_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: homelight_product_production_cable
    migrations_paths: db/cable_migrate
