name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  install_dependencies_and_run_migrations:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432
      - run: |
          if git diff --name-only origin/main... | grep -E "^Gemfile(\.lock)?$" >/dev/null; then
            bundle
            if git status | grep Gemfile.lock >/dev/null; then
              git config user.name "Eng Login"
              git config user.email "eng-login@homelight.com"
              git add Gemfile.lock
              git commit -m "dependency updates"
              git push
            else
              echo "Gemfile.lock unchanged. Skipping git commands."
            fi
          else
            echo "Gemfile unchanged. Skipping bundle install."
          fi
          if git diff --name-only origin/main... | grep db/migrate >/dev/null; then
            bundle exec bin/rails db:create db:migrate
            if git status | grep schema.rb >/dev/null; then
              git config user.name "Eng Login"
              git config user.email "eng-login@homelight.com"
              git add db/schema.rb
              git commit -m "db migrations"
              git push
            else
              echo "Schema.rb unchanged. Skipping git commands."
            fi
          else
            echo "db/migrate directory unchanged. Skipping migration commands."
          fi

  scan_ruby:
    needs: install_dependencies_and_run_migrations
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bin/brakeman --no-pager

  scan_js:
    needs: install_dependencies_and_run_migrations
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Scan for security vulnerabilities in JavaScript dependencies
        run: bin/importmap audit

  lint:
    needs: install_dependencies_and_run_migrations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Lint code for consistent style
        run: bin/rubocop -f github

  test:
    needs: install_dependencies_and_run_migrations
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y build-essential git libyaml-dev pkg-config google-chrome-stable

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Run tests
        id: runtests
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:postgres@localhost:5432
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: bin/rails db:setup spec

      - name: Keep screenshots from failed system tests
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: ${{ github.workspace }}/tmp/screenshots
          if-no-files-found: ignore

  deploy-staging:
    needs: install_dependencies_and_run_migrations
    runs-on: ubuntu-latest

    steps:
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y build-essential git libyaml-dev pkg-config

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Deploy
        env:
          AWS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET: ${{ secrets.AWS_SECRET_KEY_ID }}
        run: ./script/build_and_deploy.sh staging
